In [51]:
from tensorflow.keras.preprocessing.text import one_hot

In [52]:
### sentences
sentance=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
    ]

In [53]:
##define the vocabolory size
voc_size = 10000

In [54]:
##One hot representation
one_hot_representation = [one_hot(words, voc_size) for words in sentance]
one_hot_representation

[[4622, 7263, 1473, 3279],
 [4622, 7263, 1473, 2875],
 [4622, 7754, 1473, 4364],
 [4460, 2584, 7613, 3921, 3845],
 [4460, 2584, 7613, 3921, 819],
 [687, 4622, 6194, 1473, 2801],
 [7278, 6212, 147, 3921]]

In [55]:
##word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [56]:
import numpy as np

In [57]:
max_sentence_length = 8
embedded_docs = pad_sequences(one_hot_representation, padding="pre", maxlen=max_sentence_length)
embedded_docs

array([[   0,    0,    0,    0, 4622, 7263, 1473, 3279],
       [   0,    0,    0,    0, 4622, 7263, 1473, 2875],
       [   0,    0,    0,    0, 4622, 7754, 1473, 4364],
       [   0,    0,    0, 4460, 2584, 7613, 3921, 3845],
       [   0,    0,    0, 4460, 2584, 7613, 3921,  819],
       [   0,    0,    0,  687, 4622, 6194, 1473, 2801],
       [   0,    0,    0,    0, 7278, 6212,  147, 3921]], dtype=int32)

In [58]:
##feature representation
dimension = 10

In [65]:
model = Sequential()
model.add(Embedding(voc_size, dimension))
model.build(input_shape=(None, max_sentence_length))
model.compile("adam", "mse")

In [66]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[[ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.01765217,  0.01570631, -0.02485337, -0.03259583,
         -0.03571631,  0.02437273,  0.00414563, -0.0246393 ,
          0.00909941,  0.019881  ],
        [-0.03870528,  0.00923456, -0.01178948,  0.04462917,
         -0.04350163, -0.03907838, -0.03946656,  0.0295209 ,
          0.02091218,  0.01420945],
        [-0.00497928,  0.02101494,  0.03552229, -0.0

In [71]:
embedded_docs[0]

array([   0,    0,    0,    0, 4622, 7263, 1473, 3279], dtype=int32)

In [75]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.02120486, -0.00432819, -0.04721004, -0.02004536,
          0.01158718, -0.03955762,  0.01688265,  0.02483327,
          0.00027005, -0.02484515],
        [ 0.01765217,  0.01570631, -0.02485337, -0.03259583,
         -0.03571631,  0.02437273,  0.00414563, -0.0246393 ,
          0.00909941,  0.019881  ],
        [-0.03870528,  0.00923456, -0.01178948,  0.04462917,
         -0.04350163, -0.03907838, -0.03946656,  0.0295209 ,
          0.02091218,  0.01420945],
        [-0.00497928,  0.02101494,  0.03552229, -0.0